package ApartadoGrafico;

import java.awt.BorderLayout;
import javax.swing.JPanel;

public class JPanelOrden extends javax.swing.JPanel { 
    
    public JPanelOrden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCargarOrden = new javax.swing.JButton();
        jButtonModificarOrden = new javax.swing.JButton();
        jButtonConsultarOrden = new javax.swing.JButton();

        setBackground(new java.awt.Color(218, 243, 234));

        jButtonCargarOrden.setBackground(new java.awt.Color(247, 244, 232));
        jButtonCargarOrden.setText("Cargar Orden");
        jButtonCargarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarOrdenActionPerformed(evt);
            }
        });

        jButtonModificarOrden.setBackground(new java.awt.Color(247, 244, 232));
        jButtonModificarOrden.setText("Modificar Orden");
        jButtonModificarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarOrdenActionPerformed(evt);
            }
        });

        jButtonConsultarOrden.setBackground(new java.awt.Color(247, 244, 232));
        jButtonConsultarOrden.setText("Consultar Orden");
        jButtonConsultarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCargarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButtonCargarOrden)
                .addGap(50, 50, 50)
                .addComponent(jButtonModificarOrden)
                .addGap(50, 50, 50)
                .addComponent(jButtonConsultarOrden)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarOrdenActionPerformed
        mensajeAviso("""
                     La funcion a la que ha intentado ingresar se encuentra en desarrollo.
                     Por favor, intente nuevamente m\u00e1s tarde.""","ERROR - FUNCION NO DISPONIBLE");
    }//GEN-LAST:event_jButtonCargarOrdenActionPerformed

    private void jButtonModificarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarOrdenActionPerformed
        mensajeAviso("""
                     La funcion a la que ha intentado ingresar se encuentra en desarrollo.
                     Por favor, intente nuevamente m\u00e1s tarde.""","ERROR - FUNCION NO DISPONIBLE");
    }//GEN-LAST:event_jButtonModificarOrdenActionPerformed

    private void jButtonConsultarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarOrdenActionPerformed
        mensajeAviso("""
                     La funcion a la que ha intentado ingresar se encuentra en desarrollo.
                     Por favor, intente nuevamente m\u00e1s tarde.""","ERROR - FUNCION NO DISPONIBLE");
    }//GEN-LAST:event_jButtonConsultarOrdenActionPerformed
    
    private static void mensajeAviso(String mensaje, String titulo){
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarOrden;
    private javax.swing.JButton jButtonConsultarOrden;
    private javax.swing.JButton jButtonModificarOrden;
    // End of variables declaration//GEN-END:variables
}
