package ApartadoGrafico;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JPanel;

public class JPanelPaciente extends javax.swing.JPanel {
    
    JPanel aux;
    
    public JPanelPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCargarPaciente = new javax.swing.JButton();
        jButtonConsultarPaciente = new javax.swing.JButton();
        jButtonModificarPaciente = new javax.swing.JButton();

        setBackground(new java.awt.Color(218, 243, 234));

        jButtonCargarPaciente.setBackground(new java.awt.Color(247, 244, 232));
        jButtonCargarPaciente.setText("Cargar Paciente");
        jButtonCargarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarPacienteActionPerformed(evt);
            }
        });

        jButtonConsultarPaciente.setBackground(new java.awt.Color(247, 244, 232));
        jButtonConsultarPaciente.setText("Consultar Paciente");
        jButtonConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarPacienteActionPerformed(evt);
            }
        });

        jButtonModificarPaciente.setBackground(new java.awt.Color(247, 244, 232));
        jButtonModificarPaciente.setText("Modificar Paciente");
        jButtonModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCargarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButtonModificarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButtonCargarPaciente)
                .addGap(50, 50, 50)
                .addComponent(jButtonConsultarPaciente)
                .addGap(50, 50, 50)
                .addComponent(jButtonModificarPaciente)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarPacienteActionPerformed
        JPanelCargarPaciente panel = new JPanelCargarPaciente();     
        showPanel(panel);
    }//GEN-LAST:event_jButtonCargarPacienteActionPerformed

    private void jButtonConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarPacienteActionPerformed
        mensajeAviso("""
                     La funcion a la que ha intentado ingresar se encuentra en desarrollo.
                     Por favor, intente nuevamente m\u00e1s tarde.""","ERROR - FUNCION NO DISPONIBLE");
    }//GEN-LAST:event_jButtonConsultarPacienteActionPerformed

    private void jButtonModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPacienteActionPerformed
        mensajeAviso("""
                     La funcion a la que ha intentado ingresar se encuentra en desarrollo.
                     Por favor, intente nuevamente m\u00e1s tarde.""","ERROR - FUNCION NO DISPONIBLE");
    }//GEN-LAST:event_jButtonModificarPacienteActionPerformed

    private static void mensajeAviso(String mensaje, String titulo){
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void showPanel(JPanel p){
        p.setSize(700,500);
        p.setLocation(0,0);
        aux.removeAll();
        aux.add(p, BorderLayout.CENTER);
        aux.revalidate();
        aux.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarPaciente;
    private javax.swing.JButton jButtonConsultarPaciente;
    private javax.swing.JButton jButtonModificarPaciente;
    // End of variables declaration//GEN-END:variables
}
